jobs:
  - name: dataworks-development-tools-pr
    plan:
      - get: dataworks-development-tools-pr
        trigger: true
        version: every
      - put: dataworks-development-tools-pr
        params:
          path: dataworks-development-tools-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          dataworks-development-tools: dataworks-development-tools-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          dataworks-development-tools: dataworks-development-tools-pr
        params:
          TF_WORKSPACE: 'default'
          DETAILED_EXIT_CODE: ''
        on_failure:
          put: dataworks-development-tools-pr
          params:
            path: dataworks-development-tools-pr
            status: failure
        on_success:
          put: dataworks-development-tools-pr
          params:
            path: dataworks-development-tools-pr
            status: success
